
<h1><?php echo $this->title; ?></h1>

<?php

    // Fasteest than form-old.phtml

    $form = $this->form;

    $form->prepare();

    $form->setAttributes(array(
        //'action' => $this->basePath(). "/get-form",
        'action' => '',
        'method' => 'post',
        'class' => 'form-inline',
        'role' => 'form',
    ));

    $formLabel = $this->plugin("formLabel");

    echo $this->form()->openTag($form);

    echo $this->formCollection($form);

    echo $this->form()->closeTag();

?>